"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.30.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import base64
import binascii
import os
import sys
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from the project-level .env file before any
# setting reads from the environment. Secrets and keys live there, never in code.
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ['SECRET_KEY']

# Production mode is toggled by an environment flag so the same codebase runs
# over plain http locally and fully hardened when deployed.
PRODUCTION = os.environ.get('DJANGO_PRODUCTION', 'false').lower() == 'true'

# True while running the test suite, detected from the management command so no
# extra flag is needed. Used only to swap in a fast password hasher below.
TESTING = 'test' in sys.argv

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = not PRODUCTION

# Hosts are read from the environment so a deployment domain (e.g. the
# PythonAnywhere subdomain) can be added at deploy time while localhost keeps
# working in development.
ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get('DJANGO_ALLOWED_HOSTS', '127.0.0.1,localhost').split(',')
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'records',
    'audit',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # Placed after AuthenticationMiddleware so request.user is already resolved
    # when the audit layer reads the acting user for each request.
    'audit.middleware.AuditMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'core' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'accounts.context_processors.user_role',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'core' / 'static']

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Authentication
# The login page doubles as the site landing page (see accounts.urls).

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/'


# Session and CSRF cookie hardening. HttpOnly keeps cookies out of reach of
# client-side scripts; SameSite limits cross-site sending. These hold in every
# environment.
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Lax'

# Always-on protections that do not interfere with http development.
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

# HTTPS-only protections. Gated on PRODUCTION so local http development still
# works; switched on together when deployed behind TLS.
SESSION_COOKIE_SECURE = PRODUCTION
CSRF_COOKIE_SECURE = PRODUCTION
SECURE_SSL_REDIRECT = PRODUCTION
# Tell the app it is behind TLS terminated by the platform proxy.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https') if PRODUCTION else None
# One year of HSTS, covering subdomains, only in production.
SECURE_HSTS_SECONDS = 31536000 if PRODUCTION else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = PRODUCTION
SECURE_HSTS_PRELOAD = PRODUCTION


# Passwords use Django's default PBKDF2-SHA256 in every real environment. The
# test suite swaps in a fast (insecure) hasher purely to keep the run quick;
# this branch is never taken outside "manage.py test".
if TESTING:
    PASSWORD_HASHERS = ['django.contrib.auth.hashers.MD5PasswordHasher']


# AES-256 field-encryption key for records.EncryptedTextField. Decoded and
# length-checked here so a missing or malformed key stops the app at startup
# rather than silently storing unprotected or corrupt data.
_raw_encryption_key = os.environ.get('ENCRYPTION_KEY')
if not _raw_encryption_key:
    raise ImproperlyConfigured(
        'ENCRYPTION_KEY is not set. Add a base64-encoded 32-byte key to your .env file.'
    )
try:
    ENCRYPTION_KEY = base64.b64decode(_raw_encryption_key, validate=True)
except (binascii.Error, ValueError):
    raise ImproperlyConfigured('ENCRYPTION_KEY must be valid base64.')
if len(ENCRYPTION_KEY) != 32:
    raise ImproperlyConfigured('ENCRYPTION_KEY must decode to exactly 32 bytes for AES-256.')
