# Generated by Django 4.2.30 on 2026-07-01 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import records.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other'), ('U', 'Prefer not to say')], max_length=1)),
                ('matric_number', models.CharField(max_length=30, unique=True)),
                ('department', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('emergency_contact', models.CharField(help_text='Name and phone number of the emergency contact.', max_length=150)),
                ('assigned_counselor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_students', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='MentalHealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('assessment', 'Assessment'), ('session', 'Session'), ('note', 'Note')], max_length=20)),
                ('content', records.fields.EncryptedTextField()),
                ('date_assessed', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('counselor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authored_records', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='records.studentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
